### ISSUE TITLE
Multiple tests failure due to system localization

### ISSUE THREAD

**Issue by remz1337** [GMUEClab/ecj#63]
Multiple tests are failing when the default symbol for decimals is not `.`

Issue happened on my Windows machine, having my localization set as French (Canada) where the decimal symbol is `,`. Simply switching my localization to English (US) solved the issue, but I think it should atleast be documented somewhere.

Thanks

**Comment by SigmaX** [comment]
Hi Rémi—thanks for reporting this.  Do you recall an example of one of the failing tests, so we can look back at it and understand what's causing it?  Perhaps a `.params` file that specifies a `double` parameter with decimals?

**Comment by remz1337** [comment]
Here are some examples of the failing test:
ProportionateComponentSelector:`java.lang.NullPointerException`
`at ec.app.knapsack.KnapsackProblem.setup(KnapsackProblem.java:57)`
`at ec.co.ant.ProportionateComponentSelectorTest.setUp(ProportionateComponentSelectorTest.java:58)`

AppTest (moosuite\qv.params):
`java.lang.NullPointerException`
`at ec.multiobjective.MultiObjectiveFitness.paretoDominates(MultiObjectiveFitness.java:365)`
`at ec.multiobjective.HypervolumeStatistics.exclusiveHypervolume(HypervolumeStatistics.java:120)`
`at ec.multiobjective.HypervolumeStatistics.hypervolume(HypervolumeStatistics.java:95)`
`at ec.multiobjective.MultiObjectiveStatistics.postEvaluationStatistics(MultiObjectiveStatistics.java:133)`
