### ISSUE TITLE
Parallel Processes: java.io.EOFException

### ISSUE THREAD

**Issue by ZvikaZ** [GMUEClab/ecj#80]
I'm trying to to use parallel processes, as described at chapter 6 of the manual. The slave errors with:

	FATAL ERROR:
	Unable to read the subpop number from the master:
	java.io.EOFException
	FATAL ERROR:
	Unable to read type of evaluation from master.  Maybe the master closed its socket and exited?:
	ec.util.Output$OutputExitException:
	Exception in thread "MainThread: " ec.util.Output$OutputExitException:
			at ec.util.Output.exitWithError(Output.java:133)
			at ec.util.Output.fatal(Output.java:544)
			at ec.eval.Slave.main(Slave.java:523)

The master shows:

	 Slave attempts to connect.
	Slave /127.0.0.1/0 connected successfully.
	FATAL ERROR:
	There are no individuals with a valid fitness (that is, with their evaluated set); Cannot compute best-so-far statistics

In the master's params file, I added:

    # parallel eval processing (master/slave)
    eval.masterproblem = ec.eval.MasterProblem
    eval.master.port = 15000
    eval.masterproblem.job-size = 1
    eval.masterproblem.max-jobs-per-slave = 1
    eval.compression = false
    evalthreads = 1

and the slave params file is:

    parent.0 = sample.params
    eval.master.host = localhost
    eval.return-inds = false

If you want to run it yourself, the problem is demonstrated at my sample ecj repo: https://github.com/ZvikaZ/ECJ-sample , the branch `PARALLEL`. 

I have seen the problem both with Linux and Windows machines. At the beginning I used two different Linux machines, but then I changed the the slave to run on the same machine, and connect to `localhost` to eliminate "noise".

BTW, it's interesting to note that initially I tried with a more complex repo (https://github.com/ZvikaZ/BPGP-wumpus, branch `MASTER_SLAVE`), and it failed similarly in the slave side - however, it was worse - because the master process didn't recognize that there was an error.

**Comment by eclab** [comment]
Running on MacOS High Sierra (thus Java 8)

1. I downloaded and compiled your sample repo (btw, don't use 'var', it's not available on versions of Java for certain MacOS versions, such as mine)
2. I copied sample.params to master.params
3. I added this to the end of it:

    eval.masterproblem = ec.eval.MasterProblem
    eval.master.port = 15000
    eval.masterproblem.job-size = 1
    eval.masterproblem.max-jobs-per-slave = 1
    eval.compression = false
    evalthreads = 1

4. I made a file called slave.params, containing:

    parent.0 = sample.params
    eval.master.host = localhost
    eval.return-inds = false

5. I ran java ec.Evolve -file master.params
6. I ran java ec.Evolve -file slave.params

Worked great.  So I'm not sure what to say.  Now I have a few minor changes in my ECJ code that's not on the repository, but they're all with respect to the GroupedProblemForm hack I'm not sure I want to make official: they're pretty minor too.  I don't think that's it.

There wouldn't be any "noise" -- sockets are guaranteed fail-fast.  Do you have some kind of monitor preventing socket transmission without permission?

Sean

**Comment by ZvikaZ** [comment]
Hi.
Have you been able to reproduce the issue? Meanwhile, I've tried with Java 8, and it behaved the same.

**Comment by ZvikaZ** [comment]
I've followed what you wrote here, and it fails with the same error.
Is it possible that its OS-related? 
Maybe ECJ's current master-slave code works only on Macs, and not on Windows and Linuxes (I've tried both)?
Or maybe it's something specific to your JDK (again, I've tried few JDK versions, neither helped...) 

Can you please check this on some Linux machine?
Or maybe provide me with a clean example, that I can check on my machines?

**Comment by ZvikaZ** [comment]
> Just did a test on a large redhat server of ours. Works great. Here's what I'm using.

1. That's great news! Do you happen to know what redhat version is it? I want to try it as well.
2. Maybe your answer was truncated? I see the sentence `Here's what I'm using.` without further details.
3. Did you run the same test as described above (based on my environment, with your minor changes), or was it something else (if that's the case, can you please give details, so I can try it as well)?
4. I've read again our discussion, and encountered:
>  Now I have a few minor changes in my ECJ code that's not on the repository, but they're all with respect to the GroupedProblemForm hack I'm not sure I want to make official: they're pretty minor too

it's possible that these changes are the cause of the difference between my runs and yours. Can you please commit what you're working on (even as a temporary branch, not `master`), so we can make sure it's really not related? (or, can you test with clean ecj release?)
